### ISSUE TITLE
react-native-shimmer

### ISSUE THREAD

**Issue by olivierlesnicki** [facebook/Shimmer#54]
What abouta react-native package for Shimmer?

**Comment by atom2ueki** [comment]
+1

**Comment by grp** [comment]
This would be cool, but probably best as a separate repository from this one. I've asked around internally if the RN team has anything for Shimmer specifically and I'll let you know what I hear.

**Comment by brianjd** [comment]
@grp Any updates you can share?

**Comment by Jpadilla1** [comment]
Hey guys, I just released a React Native package for this library if you want to check it out https://github.com/Jpadilla1/rn-shimmer

**Comment by oblador** [comment]
My wrapper has been out for a few weeks on npm: [react-native-shimmer](https://www.npmjs.com/package/react-native-shimmer). No swift dependency, CocoaPods support and documented.
