### ISSUE TITLE
Not compatible with arm64?

### ISSUE THREAD

**Issue by charlesfries** [facebook/Shimmer#59]
Trying to get Shimmer to work in my Swift project using a bridging header. When I try to implement a FBShimmeringView object in my controller, the linker throws this error:

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FBShimmeringView", referenced from:
      type metadata accessor for __ObjC.FBShimmeringView in FeaturedViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Am I correct in assuming this framework is incompatible with the latest iPhone 64-bit processors, or am I missing something here?

**Comment by grp** [comment]
Shimmer fully supports 64-bit compilation for ARM and x86.

In this case, it looks like you aren't building the source code for Shimmer into your project, only just including the headers with the declarations. You didn't mention if you're using it, but we suggest using CocoaPods to install Shimmer which would avoid many common integration mistakes.
