### ISSUE TITLE
About FBShimer 

### ISSUE THREAD

**Issue by ncncff51131420** [facebook/Shimmer#62]
I have tried many times ,but I can't see the shimmering effect when launch your project.
all the code is  the same as  when it  was downloaded. 
please give me  a hand.

**Comment by grp** [comment]
It would be great to see a screenshot or a description of what you do see.

**Comment by ncncff51131420** [comment]
Thank you,wait me for a moment.

**Comment by ncncff51131420** [comment]
excuse me ，how can I take a screenshot for you to see. seems that couldn't

**Comment by ncncff51131420** [comment]
[Uploading Shimmer-master 2.zip…]()

**Comment by grp** [comment]
This might be helpful: http://stackoverflow.com/questions/7092613/take-screenshots-in-the-ios-simulator

**Comment by ncncff51131420** [comment]
Could  you give me another demo of Shimmer, network speed is so slow!

**Comment by ncncff51131420** [comment]
It's realy very nice of you!

**Comment by liujiangding** [comment]
I do not want to receive your email anymore！！！！


2

**Comment by ncncff51131420** [comment]
[](http://blog.csdn.net/ncncff51131420/article/details/51743309)

**Comment by ncncff51131420** [comment]
http://blog.csdn.net/ncncff51131420/article/details/51743309

**Comment by ncncff51131420** [comment]
The above url is where the problem is ,hope for your answer:@  Mr grp

**Comment by grp** [comment]
The text "Shimmer" at the bottom should be shimmering. You may need to click the screen once to unpause it.

**Comment by ncncff51131420** [comment]
Sorry，still cannot shimmering ,I downloaded your demo, checked and clicked several times.   can't see the effect.

**Comment by b3ll** [comment]
Not sure why your demo isn't working, I just double checked and it is indeed working:

[shimmer.zip](https://github.com/facebook/Shimmer/files/332388/shimmer.zip)
